# -*- coding: utf-8 -*-
"""facial recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cgHCl2qeIykggfx9rIcSfJqRRxsjOruk
"""

pip install mtcnn

from PIL import Image
import numpy as np
from mtcnn.mtcnn import MTCNN
from os import listdir
from matplotlib import pyplot

def extract_face(filename, required_size=(160,160)):
  image = Image.open(filename)
  image = image.convert('RGB')
  pixels = np.asarray(image)
  detector = MTCNN()
  results = detector.detect_faces(pixels)
  #extracting bounding boxes from face
  x1 ,y1 ,width, height = results[0]['box']
  #bug fix
  x1, y1 = abs(x1), abs(y1)
  x2 ,y2 = x1 + width, y1 + height

  face = pixels[y1:y2, x1:x2]
  image = Image.fromarray(face)
  image = image.resize(required_size)
  face_array = np.asarray(image)
  return face_array

from google.colab import drive
drive.mount('/content/drive')
folder = '/content/drive/My Drive/5-celebrity-faces-dataset/train/ben_afflek/'
i = 1
for filename in listdir(folder):
  path = folder + filename
  face = extract_face(path)
  print(i, face.shape)
  pyplot.subplot(2, 7, i)
  pyplot.axis('off')
  pyplot.imshow(face)
  i += 1
pyplot.show